# Tomorrow Night Bright
[colors]
foreground = "#eaeaea"
background = "#f4bf75"
cursor_bg = "#eaeaea"
cursor_border = "#eaeaea"
cursor_fg = "#f4bf75"
selection_bg = "#424242"
selection_fg = "#eaeaea"

ansi = ["#f4bf75","#d54e53","#b9ca4a","#e7c547","#7aa6da","#c397d8","#70c0b1","#ffffff"]
brights = ["#f4bf75","#d54e53","#b9ca4a","#e7c547","#7aa6da","#c397d8","#70c0b1","#ffffff"]

