[manager]
show_hidden = true

[opener]
edit = [
    { run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'vlc "$@"', orphan = true, for = "unix" },
]
image=[
    {run = 'nsxiv "$@"', block = true}
]
[open]
rules = [
	{ name = "*.jpg", use = ["image"] },
	{ name = "*.png", use = ["image"] },
]
