# Colors (Batman)

[colors.bright]
black = '#505354'
blue = '#919495'
cyan = '#a3a3a6'
green = '#fff27d'
magenta = '#9a9a9d'
red = '#fff78e'
white = '#dadbd6'
yellow = '#feed6c'

[colors.cursor]
cursor = '#fcef0c'
text = '#000000'

[colors.normal]
black = '#1b1d1e'
blue = '#737174'
cyan = '#62605f'
green = '#c8be46'
magenta = '#747271'
red = '#e6dc44'
white = '#c6c5bf'
yellow = '#f4fd22'

[colors.primary]
background = '#1b1d1e'
foreground = '#6f6f6f'

[colors.selection]
background = '#4d504c'
text = '#f0e04a'


# # Colors (Custom)
#
# [colors]
# foreground = "#d8d8d8"
# background = "#181818"
# dim_foreground = "#828482"
# bright_foreground = "None"
# cursor = { text = "CellBackground", cursor = "CellForeground" }
# foreground = "<string>"
# background = "<string>"
# dim_foreground = "<string>"
# bright_foreground = "<string>"
#
# [colors.normal]
# black = "#181818"
# red = "#ac4242"
# green = "#90a959"
# yellow = "#f4bf75"
# blue = "#6a9fb5"
# magenta = "#aa759f"
# cyan = "#75b5aa"
# white = "#d8d8d8"
#
# [colors.bright]
# black = "#6b6b6b"
# red = "#c55555"
# green = "#aac474"
# yellow = "#feca88"
# blue = "#82b8c8"
# magenta = "#c28cb8"
# cyan = "#93d3c3"
# white = "#f8f8f8"
#
# [colors.dim]
# black = "#0f0f0f"
# red = "#712b2b"
# green = "#5f6f3a"
# yellow = "#a17e4d"
# blue = "#456877"
# magenta = "#704d68"
# cyan = "#4d7770"
# white = "#8e8e8e"
#
# [colors.hints]
# start = { foreground = "#181818", background = "#f4bf75" }
# end = { foreground = "#181818", background = "#ac4242" }
#
# [colors.search]
# matches = { foreground = "#181818", background = "#ac4242" }
# focused_match = { foreground = "#181818", background = "#f4bf75" }
#

