#!/usr/bin/env bash
#
# power-profiles-daemon implementation:
# needs package power-profiles-daemon installed and the service running see here:
# https://wiki.archlinux.org/title/CPU_frequency_scaling#power-profiles-daemon
# used in i3-blocks: ~/.config/i3/i3blocks.conf together with: ~/.config/i3/scripts/power-profiles

# script to show current power profile

current_profile=$(/usr/bin/powerprofilesctl get)

if [ $current_profile == "balanced" ]; then
    echo "󰌪 $current_profile"
elif [ $current_profile == "performance" ]; then
    echo "󱐋 $current_profile"
elif [ $current_profile == "power-saver" ]; then
    echo "󰔱 $current_profile"
fi
