#!/usr/bin/bash

if pgrep -x "screenkey" > /dev/null
then
    killall screenkey
else
    screenkey --geometry 600x80-10-10 --font-size medium --persist --opacity 0.3 --key-mode translated --position fixed &
fi
